name: 'Build Awesome Website'
description: 'Builds the Awesome Website from a user-provided YAML file.'
branding:
  icon: book-open
  color: orange
inputs:
  yaml-path:
    description: 'Path to the YAML file to use as data source.'
    required: true
  base-path:
    description: 'Optional base path (e.g. /my-site/) to host under. Default is the repository name.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: checkout awesome website source
      uses: actions/checkout@v4
      with:
        repository: raideno/awesome-website
        ref: main
        path: awesome-website-src

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install dependencies
      run: |
        cd awesome-website-src
        npm ci
      shell: bash

    - name: copy user YAML file
      run: |
        cp ${{ github.workspace }}/${{ inputs.yaml-path }} awesome-website-src/list.yaml
      shell: bash

    - name: determine BASE_PATH
      id: base
      run: |
        if [ -n "${{ inputs.base-path }}" ]; then
          echo "value=${{ inputs.base-path }}" >> "$GITHUB_OUTPUT"
        else
          REPO_NAME=$(basename "${GITHUB_REPOSITORY_URL}")
          echo "value=/$REPO_NAME/" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: build awesome website
      env:
        BASE_PATH: ${{ steps.base.outputs.value }}
        LIST_FILE_PATH: list.yaml
        # TODO: might cause an issue
        GITHUB_REPOSITORY_URL: ${{ secrets.GITHUB_REPOSITORY_URL }}
      run: |
        cd awesome-website-src
        npm run build
      shell: bash
