name: "Build Awesome Website"
description: "Builds the Awesome Website from a user-provided YAML file."
branding:
  icon: book-open
  color: orange
inputs:
  yaml-path:
    description: "Path to the YAML file to use as data source."
    required: true
  base-path:
    description: "Optional base path (e.g. /my-site/) to host under. Default is the repository name."
    required: false
runs:
  using: "composite"
  steps:
    - name: checkout awesome website source
      uses: actions/checkout@v4
      with:
        repository: raideno/awesome
        ref: main
        path: awesome-src

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: install dependencies
      run: |
        cd awesome-src
        npm ci
      shell: bash

    - name: copy user YAML file
      run: |
        cp ${{ github.workspace }}/${{ inputs.yaml-path }} awesome-src/packages/website/${{ inputs.yaml-path }}
        # Copy README.md if it exists in the same directory as the YAML file
        YAML_DIR=$(dirname "${{ github.workspace }}/${{ inputs.yaml-path }}")
        if [ -f "$YAML_DIR/README.md" ]; then
          cp "$YAML_DIR/README.md" awesome-src/packages/website/$(dirname "${{ inputs.yaml-path }}")/README.md
          echo "README.md copied"
        else
          echo "No README.md found, skipping"
        fi
      shell: bash

    - name: determine BASE_PATH
      id: base
      run: |
        if [ -n "${{ inputs.base-path }}" ]; then
          echo "value=${{ inputs.base-path }}" >> "$GITHUB_OUTPUT"
        else
          echo "value=/${{ github.event.repository.name }}/" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: get user repository commit hash
      id: user-commit
      run: |
        echo "hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: get awesome commit hash
      id: awesome-commit
      run: |
        cd awesome-src
        echo "hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: build awesome website
      env:
        BASE_PATH: ${{ steps.base.outputs.value }}
        LIST_FILE_PATH: ${{ inputs.yaml-path }}
        GITHUB_REPOSITORY_URL: https://github.com/${{ github.repository }}
        USER_REPOSITORY_COMMIT_HASH: ${{ steps.user-commit.outputs.hash }}
        AWESOME_WEBSITE_COMMIT_HASH: ${{ steps.awesome-commit.outputs.hash }}
        GITHUB_WORKFLOW_NAME: ${{ github.workflow }}
        GITHUB_WORKFLOW_REF: ${{ github.workflow_ref }}
      run: |
        cd awesome-src
        npm run build --workspace website
      shell: bash

    - name: backward compatibility
      run: |
        mkdir -p awesome-website-src
        cp -r awesome-src/packages/website/dist awesome-website-src/dist
      shell: bash
