/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as PagesTermsOfServiceRouteImport } from './routes/pages/terms-of-service'
import { Route as PagesPrivacyPolicyRouteImport } from './routes/pages/privacy-policy'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardPaymentIndexRouteImport } from './routes/_authenticated/dashboard/payment/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesTermsOfServiceRoute = PagesTermsOfServiceRouteImport.update({
  id: '/pages/terms-of-service',
  path: '/pages/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPrivacyPolicyRoute = PagesPrivacyPolicyRouteImport.update({
  id: '/pages/privacy-policy',
  path: '/pages/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardPaymentIndexRoute =
  AuthenticatedDashboardPaymentIndexRouteImport.update({
    id: '/dashboard/payment/',
    path: '/dashboard/payment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/privacy-policy': typeof PagesPrivacyPolicyRoute
  '/pages/terms-of-service': typeof PagesTermsOfServiceRoute
  '/explore': typeof ExploreIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/payment': typeof AuthenticatedDashboardPaymentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/privacy-policy': typeof PagesPrivacyPolicyRoute
  '/pages/terms-of-service': typeof PagesTermsOfServiceRoute
  '/explore': typeof ExploreIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/payment': typeof AuthenticatedDashboardPaymentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/pages/privacy-policy': typeof PagesPrivacyPolicyRoute
  '/pages/terms-of-service': typeof PagesTermsOfServiceRoute
  '/explore/': typeof ExploreIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/payment/': typeof AuthenticatedDashboardPaymentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/explore'
    | '/dashboard'
    | '/dashboard/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/explore'
    | '/dashboard'
    | '/dashboard/payment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/pages/privacy-policy'
    | '/pages/terms-of-service'
    | '/explore/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/payment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PagesPrivacyPolicyRoute: typeof PagesPrivacyPolicyRoute
  PagesTermsOfServiceRoute: typeof PagesTermsOfServiceRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/terms-of-service': {
      id: '/pages/terms-of-service'
      path: '/pages/terms-of-service'
      fullPath: '/pages/terms-of-service'
      preLoaderRoute: typeof PagesTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/privacy-policy': {
      id: '/pages/privacy-policy'
      path: '/pages/privacy-policy'
      fullPath: '/pages/privacy-policy'
      preLoaderRoute: typeof PagesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/payment/': {
      id: '/_authenticated/dashboard/payment/'
      path: '/dashboard/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardPaymentIndexRoute: typeof AuthenticatedDashboardPaymentIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardPaymentIndexRoute:
    AuthenticatedDashboardPaymentIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PagesPrivacyPolicyRoute: PagesPrivacyPolicyRoute,
  PagesTermsOfServiceRoute: PagesTermsOfServiceRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
