name: validate awesome list schema

on:
  pull_request:
  push:
    branches: ['*']

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm ci

      - name: generate schema
        run: node --import tsx scripts/gen-schema.ts

      - name: check for schema changes
        run: |
          if ! git diff --exit-code awesome.list.schema.json; then
            echo "[error]: awesome.list.schema.json is out of date. Please run 'node scripts/gen-schema.ts' and commit the changes." >&2
            exit 1
          fi
